### ISSUE TITLE
Not required for emacs-plus formula

### ISSUE THREAD

**Issue by Andre0991** [LionyxML/auto-dark-emacs#11]
Hi. I have been using this package for a few months and it has been super useful.

However, after reading the options provided by the `emacs-plus` [1] formula, I see that it provides a hook for when the system appearance is changed.

This is arguabily nicer than a pull mechanism, which is implemented by `auto-dark-emacs`.
So, I’m wondering if it would make sense to document in `auto-dark-emacs` README that `emacs-mac` users should use the hook instead, while this package could be useful for other Emacs versions for ns.

Thanks!

[1]: https://github.com/d12frosted/homebrew-emacs-plus#system-appearance-change

**Comment by LionyxML** [comment]
Hello there!

This is a really good Idea. I'll sure consider including this feature. I'll just have to make sure I won't break anything :)

Thanks!

**Comment by LionyxML** [comment]
@Andre0991 There you have it.

Just implemented it. 

Should be on MELPA now. Thanks for the heads up :)

PR: #15

**Comment by Andre0991** [comment]
Great, thanks!
