### ISSUE TITLE
Failing with "AppleScript error 1"

### ISSUE THREAD

**Issue by lukehoersten** [LionyxML/auto-dark-emacs#13]
After installation, failing with the error:
`Error running timer ‘auto-dark--check-and-set-dark-mode’: (error "AppleScript error 1")`

Please let me know if there's anything else I can do to help investigate the issue.

**Comment by marcosbodio** [comment]
I have the exact same problem:
- GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559))
 of 2022-09-12
- macOS Monterey version 12.6 (21G115), Chip Apple M1 Max

**Comment by LionyxML** [comment]
Hello there!
Thanks for your reports.

I just re-downloaded `auto-dark` from MELPA, put `(require 'auto-dark)` inside my ~/.emacs and everything seems to be working fine.

Maybe it is something with the compiled version you guys might be using? Have you tried different emacs distributions, like the emacs from brew, https://emacsformacosx.com, or this very very cool repo (https://github.com/d12frosted/homebrew-emacs-plus) ?

Two things to keep note.
1.) If you `M-x customize-group RET auto-dark RET` and toggle `Auto Dark Allow Osascript` to on, like here:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/16169950/199834353-9d2f1000-a338-49fe-8bbe-f3e81e78e88a.png">
Then close and open emacs again. Does it change anything?

2.) On MacOS settings -> security and privacy -> privacy , check each item where emacs appears if full access is granted.
Example:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/16169950/199835791-70a7f06d-d1f0-4110-9232-4de8f93267d0.png">

Here I have Emacs allowed (checked) on:
- Full Disk Access
- Files and Folders
- Automation

Also for reference I am using: 
- GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.4.0, NS appkit-2113.40 Version 12.3 (Build 21E230)) of 2022-03-21
- MacOS Monterey 12.6 (21G115), chip Apple M1

Please let me now if any of my guesses fixes anything :)

**Comment by LionyxML** [comment]
PR #15 just implemented a new behavior and it is already on MELPA.

If you guys use the `emacs-plus` brew formulae. `auto-dark-emacs` will use it's compiled plugin to detect changes instead of the old method.

Let me now if it works for you.

**Comment by marcosbodio** [comment]
@LionyxML Thank you for your suggestions. I have re-installed `auto-dark` and I have tried both (1) and (2) in your comment, and it made no difference. Unfortunately I still get the same error.

**Comment by Tyruiop** [comment]
Hi, jumping in this issue because I have the same issue after doing `brew install --cask emacs`. However, if I run emacs from alacritty, then it works perfectly, if I run it from the launcher then I have this issue. I can't seem to give permissions to emacs. Hope this can help a bit!

**Comment by guobingyi** [comment]
I have same problem,I use emacs shell-command execute command:
osascript -e 'tell application "System Events" to tell appearance preferences to return dark mode'
then allow emacs privacy.restart emasc,it be working fine.Hope this can help a bit too!Thanks [LionyxML] s(https://github.com/LionyxML) let me know osascript 😊

**Comment by marcosbodio** [comment]
> Hi, jumping in this issue because I have the same issue after doing `brew install --cask emacs`. However, if I run emacs from alacritty, then it works perfectly, if I run it from the launcher then I have this issue. I can't seem to give permissions to emacs. Hope this can help a bit!

Thank you @Tyruiop! I have tried to start emacs from the terminal (I use [iTerm2](https://iterm2.com/)) with `nohup emacs &`, and now auto-dark works :)

**Comment by LionyxML** [comment]
Yey!
Closing it. If any trouble happens in the future we may open it again.

**Comment by gopar** [comment]
> I have same problem,I use emacs shell-command execute command:
> 
> ```
> osascript -e 'tell application "System Events" to tell appearance preferences to return dark mode'
> ```
> 
> then allow emacs privacy.restart emasc,it be working fine.Hope this can help a bit too!Thanks [LionyxML](https://github.com/LionyxML) let me know osascript 😊

For whatever reason I needed to run this first, a dialog pops up asking for permission, click yes. I was unable to find it via settings. Perhaps this is something worth putting in readme? The optional `dark-mode-allow-osascript` did not help

Thanks for the work on package!
