### ISSUE TITLE
auto-dark--is-dark-mode-dbus: Symbol’s function definition is void: dbus-call-method

### ISSUE THREAD

**Issue by willmcpherson2** [LionyxML/auto-dark-emacs#22]
Hi, first of all thanks for the package. Awesome to see support for many different platforms. I'm new to Emacs so excuse me if I've got this wrong.

`M-x auto-dark-mode` fails:

```
auto-dark--is-dark-mode-dbus: Symbol’s function definition is void: dbus-call-method
```

But if I eval `(require 'dbus)`, it succeeds. We should call this at some point before we call any dbus functions.

Thanks!

**Comment by J3RN** [comment]
This is my doing; I'm working on a fix.  Weirdly I don't have to require `dbus` on one of my machines, but I do on another.
