### ISSUE TITLE
Slightly freezes on Windows

### ISSUE THREAD

**Issue by ticolensic** [LionyxML/auto-dark-emacs#30]
I'm new to emacs (well, 10 years of trying to adopt and adapt). I tried this plugin on Windows, and it slightly freezes every, I presume, run of the powershell. I sorta know why, because of a synchronous call (and this is the reason I was postponing switching to Emacs). 
I'm not sure if this is fixable, but it is still an issue. I can take a look myself if I have time.

I'm using Windows 10 22H2 and Emacs 29.

**Comment by LionyxML** [comment]
Hello there!

Thanks for trying it out!

I  have no access to a Windows machine right know. But what do you think it would be? 

It seems to be related to powershell being called synchronously and your machine running it with a little delay.

Would you like to take a look at it @seagle0128? Does this happen to you too?

**Comment by seagle0128** [comment]
I am using Emacs 29 on Windows 11, and I didn't observe this issue on my laptop.

**Comment by seagle0128** [comment]
I am using Emacs 29 on Windows 11, and I didn't observe this issue on my laptop.

**Comment by McPhale** [comment]
I'm having the same problem; took a look at the emacs process under process explorer and it does seem to be the powershell calls causing it to hang.

**Comment by ticolensic** [comment]
I finally was able to record it, mp4 instead of gif (so that there's enough frames to catch it). 
[dropbox, 883kb](https://www.dropbox.com/s/uzgc9bbwc2fdqj2/auto-dark1.mp4?dl=0)
You can see this effect on "b" lines 1, 3 and 4.

It is definitely the powershell script. I was thinking of threading it and putting the result to a global variable. I know, I know, but this could fit here, sorta a thread unsafe queue for the poor.

**Comment by seagle0128** [comment]
@ticolensic I guess it's due to the gc. Try increase `gc-cons-threshold`.

**Comment by seagle0128** [comment]
@ticolensic I guess it's due to the gc. Try increase `gc-cons-threshold`.

**Comment by LionyxML** [comment]
@ticolensic have you tried inscreasing the `gc-const-threshold`? Any luck?

**Comment by McPhale** [comment]
I had mine bumped up to 100000000 before installing the package and still had the same issue, so I doubt that's it?  Happy to do more troubleshooting.

**Comment by quienn** [comment]
PowerShell is really *that* slow. So, my suggestion is ditch it and use `cmd` instead.

Something like this should do the trick:

```cmd
reg query HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize /v AppsUseLightTheme
```

It's faster 'cause you're getting the value directly from the registry, not using a wrapper around it.

**Comment by seagle0128** [comment]
> PowerShell is really _that_ slow. So, my suggestion is ditch it and use `cmd` instead.

Agree. powershell is slower than cmd generally. The func `auto-dark--is-dark-mode-powershell` should be optimized.

**Comment by quienn** [comment]
After a couple hours trying to get my head around Elisp I got this little snippet to work:

```elisp
(defun auto-dark--is-dark-mode-powershell ()
    (string-equal "0x0"
                  (car (reverse (string-split (string-trim (shell-command-to-string "reg query HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize /v AppsUseLightTheme | findstr 0x")))))))
```

I know, it sucks. :smile: It can be optimized, but I don't have the time to do it myself.

For the people like me that were having problems using the PowerShell implementation, putting this just after `auto-dark-mode` should give a *huge* performance boost.

**Comment by seagle0128** [comment]
> Edit: Apparently, `string-split` does not exist in Vanilla Emacs. 😃 I was using Doom Emacs when testing it.

Using `compat` should work.

**Comment by LionyxML** [comment]
I'd be more then happy if anyone have the time to make a PR :)

**Comment by LionyxML** [comment]
Thanks @quienn , it is now merged!
