### ISSUE TITLE
Allow no theme as dark/light theme - i.e., (setq auto-dark-*-theme nil)

### ISSUE THREAD

**Issue by luisgerhorst** [LionyxML/auto-dark-emacs#41]
A simple if clause here 

https://github.com/LionyxML/auto-dark-emacs/blob/65cc6337de9030ea7cae4661389019b9443543a2/auto-dark.el#L164

would probably do it. Doom supports the same for `doom-theme` because the default colors are also nice:

```
doom-theme is a customizable variable defined in doom-ui.el.

Value
doom-solarized-dark

Original Value
nil

Set Customize

Documentation
A symbol representing the Emacs theme to load at startup.

Set to nil to load no theme at all. This variable is changed by
load-theme.
```

**Comment by LionyxML** [comment]
Hello there @luisgerhorst !
Is this related to your PR #40?

Sorry I didn't get what you mean. I am not familiar with doom emacs myself. Would you explain it to me?

**Comment by luisgerhorst** [comment]
Sure, no it's unrelated. This is not really related to doom, doom is just an example where this feature was implemented. Currently, there is no way to tell auto-dark-theme to use no theme as dark/light theme (i.e., unload all themes but not load any new theme). Does this make it clear?

**Comment by LionyxML** [comment]
Hey @luisgerhorst !

Yep, I got you.

A "no theme" option for ether dark and light modes is not currently implemented.

Maybe the better approach would be allowing the variables `auto-dark-dark-theme` and `auto-dark-light-theme` to be nil and treating them when `(load-theme)` is called. I'd keep the hooks working though.

**Comment by LionyxML** [comment]
@luisgerhorst , thanks for the suggestion. Closing this discussion.

`auto-dark-mode` can now use `nil` as a theme option.

**Comment by luisgerhorst** [comment]
Awesome, thank you! :)
