### ISSUE TITLE
Publish on Melpa Stable

### ISSUE THREAD

**Issue by mattiasb** [LionyxML/auto-dark-emacs#68]
Hi!

As I was looking through the code to adapt to the latest changes (great work btw!) I found that you make releases. If you tag the releases (regular `git tag`) I believe you'll be added to Melpa Stable automatically.

It's not a huge thing, but I've been pondering disabling regular Melpa and just using ELPA and Melpa Stable but there are a couple packages that I can't leave home without that I would have to vendor if that were the case. `auto-dark-mode` is one of those. :)

**Comment by LionyxML** [comment]
Nice tip @mattiasb.

We've just merged into the master and I created a tag for it `0.13.1`, usually it takes about an our to MELPA reflect updates, I don't know about the stable version.

Could you give it a try if it works for you?

**Comment by mattiasb** [comment]
Woop! https://stable.melpa.org/#/auto-dark :)
