### ISSUE TITLE
(load "server") bug

### ISSUE THREAD

**Issue by luqtas** [LionyxML/auto-dark-emacs#71]
i'm guessing it's because my init.el has `(load "server")`

but every time i open Emacs after rebooting the computer, it doesn't load the correct theme, as the previous day i was using at night and by morning, my computer changes the theme automatically. auto-dark only detects and changes themes when Emacs is open

you can reproduce the bug by opening Emacs, changing the dark-mode of your computer as you like (auto-dark works), then close it (C-x C-c), change the theme of your computer and open Emacs again

GNU Emacs 28.2, Debian 12

**Comment by LionyxML** [comment]
Hello there! Thanks for reaching out.

Could you test if adding this hook makes anything better? I had no time to test it, but something in this lines might work:

```elisp
(add-hook 'server-after-make-frame-hook
		  (lambda (frame)
			(with-selected-frame frame
			  (when (display-graphic-p)
				(auto-dark-mode 1)))))
```
I am assuming you start Emacs as a service and uses it with GUI.

**Comment by luqtas** [comment]
same result, not solved

**Comment by LionyxML** [comment]
I see it, well. Could you provide me a small reproducible init.el config and some instructions of how to recreate this behavior? 

Also, could you try setting auto-dark this way?
 
```elisp
(use-package auto-dark
  :ensure t
  :custom
  (auto-dark-themes '((wombat) (leuven)))
  :config
  (add-hook 'server-after-make-frame-hook
		  (lambda (frame)
			(with-selected-frame frame
			  (when (display-graphic-p)
				(auto-dark-mode 1))))))
```

**Comment by luqtas** [comment]
hmm, this settings says "use-package" is _void_

either the way, i was baking a init.el file but i noticed that skimming only the startup of _auto-dark_ solved my issue... i decided to take a sip and i discovered it probably has some conflict of packages as removing this part of file solves the issue,

```lisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-dark-themes '((modus-vivendi) (modus-operandi)))
 '(custom-enabled-themes nil)
 '(package-selected-packages
   '(auto-dark cl-format decide ## visual-fill-column sly multi highlight dash crdt))
 '(safe-local-variable-values
   '((eval org-toggle-inline-images)
     (eval setq org-image-actual-width 300))))
```

**Comment by LionyxML** [comment]
Cool, than it is fixed for you :)

Maybe you couldn't use the `use-package` macro because your config did not yet required it?

Perhaps you need:  
```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```

**Comment by luqtas** [comment]
i have these on my _init.el_

i installed yours manually as i'm getting `package--with-response-buffer-1: https://melpa.org/packages/auto-dark-20240914.248.tar: Not found` but i think that's a problem of my new internet provider

**Comment by LionyxML** [comment]
Added relevant section to `readme.md` (https://github.com/LionyxML/auto-dark-emacs?tab=readme-ov-file#notes-for-emacs-daemon--server-mode-users).

**Comment by nuthub** [comment]
Absolutely great, Thank you!
